import Nav from './(components)/Nav';
import './globals.css';
import { Inter } from 'next/font/google';
import { config } from '@fortawesome/fontawesome-svg-core';
import '@fortawesome/fontawesome-svg-core/styles.css';

config.autoAddCss = false;
const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Ticket App',
  description: 'Generated by David H',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex flex-col h-screen max-h-screen z-10">
          <Nav />
          <main className="flex-grow overflow-y-auto bg-page text-default-text">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
